name: Dependent Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  multiple-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step - log something
        run: |
          echo "This is the first job and first step"
  multiple-second-job:
    runs-on: ubuntu-latest
    needs: multiple-first-job
    steps:
      - name: First step - log something
        run: |
          echo "First job has been completed. Second job is started."
          echo "This is the second job and first step"
  multiple-third-job:
    runs-on: ubuntu-latest
    needs: [multiple-first-job, multiple-second-job]
    steps:
      - name: First step - log something
        run: |
          echo "First job and second job have been completed."
          echo "This is the third job and first step"
