name: First Workflows
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  first-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: |-
          echo "Hello World"
          echo "First step workflow ran successfully"
