name: Node Js Ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  first-nodejs-ci:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: |-
          echo: "Hello nodejs ci wold"
          echo: "successfully print nodejs ci"
